# Generated by Django 4.1.4 on 2023-04-11 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
